routes/web.php
<?php

Route::get('/', function () {
    return redirect('home');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
	Route::get('/home', 'HomeController@index')->name('home');
	Route::resource('pegawai', 'PegawaiController', ['except' => ['show']]);
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::resource('account', 'AccountController');
	Route::resource('kategori', 'KategoriController', ['except' => ['show']]);
	Route::resource('pemasukan', 'PemasukanController');
	Route::resource('pengeluaran', 'PengeluaranController');
	Route::resource('hutang', 'HutangController');
	Route::get('laporan', 'LaporanController@index')->name('laporan');
	Route::get('/startdate/{startdate}/enddate/{enddate}/jenis/{jenis}', ['as' => 'laporanpdf', 'uses' => 'LaporanController@laporanPDF']);
	Route::get('/table/pegawai', 'PegawaiController@dataTable')->name('table.pegawai');
	Route::get('/table/kategori', 'KategoriController@dataTable')->name('table.kategori');
	Route::get('/table/pemasukan', 'PemasukanController@dataTable')->name('table.pemasukan');
	Route::get('/table/pengeluaran', 'PengeluaranController@dataTable')->name('table.pengeluaran');
	Route::get('/table/hutang', 'HutangController@dataTable')->name('table.hutang');
	Route::get('/dashboard/countdata', 'DashboardController@dataHeader');
});

app/Hutang.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Hutang extends Model
{
    protected $table = 'hutang';

    protected $fillable = [
        'id',
        'user_id',
        'account_id',
        'pegawai_id',
        'kategori_id',
        'tanggal',
        'aktivitas',
        'jumlah',
        'bukti',
        'catatan',
        'status',
        'created_at',
    ];

    protected $hidden = [
        'updated_at',
        'deleted_at',
    ];

    public function user()
    {
        return $this->belongsTo('App\User', 'user_id', 'id');
    }

    public function account()
    {
        return $this->belongsTo('App\Account', 'account_id', 'id');
    }

    public function pegawai()
    {
        return $this->belongsTo('App\Pegawai', 'pegawai_id', 'id');
    }

    public function kategori()
    {
        return $this->belongsTo('App\Kategori', 'kategori_id', 'id');
    }

    public function getTanggalAttribute($tanggal)
    {
        return Carbon::parse($tanggal)->format('d-m-Y');
    }

    public function getJumlahAttribute($jumlah)
    {
        $jumlah = number_format($jumlah, 0, '', ',');

        return $jumlah;
    }
}

app/Http/Controllers/HutangController.php
<?php

namespace App\Http\Controllers;

use App\Account;
use App\Hutang;
use App\Kategori;
use App\Pegawai;
use App\Pengeluaran;
use Illuminate\Http\Request;
use File;
use DataTables;
use Carbon\Carbon;
use DB;

class HutangController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $hutang = Hutang::get();

        return view('hutang.index', compact('hutang'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $account = Account::all();
        $pegawai = Pegawai::all();
        $kategori = Kategori::all();
        return view('hutang.create', compact('account', 'pegawai', 'kategori'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(
            [
            'admin' => 'required',
            'tanggal' => 'required',
            'pegawai' => 'required',
            'kategori' => 'required',
            'aktivitas' => 'required|regex:/^[A-Za-z&-\/0-9 ]+$/',
            'jumlah' => 'required',
            'bukti.*' => 'image|mimes:jpeg,png,jpg|max:2048',
            ]
        );

        try {
            DB::beginTransaction();
            if ($request->hasfile('bukti')) {
                foreach ($request->file('bukti') as $file) {
                    $namafile = time() . '-' . $file->getClientOriginalName();
                    $folderhut = 'uploads/hutang/';
                    $folderkel = 'uploads/pengeluaran/';
                    $file->move('uploads/hutang', $namafile);
                    copy($folderhut.$namafile, $folderkel.$namafile);
                    $data[] = $namafile;
                }
    
                $upload = json_encode($data);
            }
    
            $request->tanggal = Carbon::parse($request->tanggal)->format('Y-m-d');
    
            Hutang::create(
                [
                'user_id' => $request->admin,
                'tanggal' => $request->tanggal,
                'account_id' => $request->account,
                'pegawai_id' => $request->pegawai,
                'kategori_id'=> $request->kategori,
                'aktivitas' => $request->aktivitas,
                'jumlah'=> str_replace( ',', '', $request->jumlah),
                'bukti' => empty($upload) ? '' : $upload,
                'catatan' => empty($request->catatan) ? '' : $request->catatan,
                'status' => $request->status,
                ]
            );
    
            Pengeluaran::create(
                [
                'user_id' => $request->admin,
                'tanggal' => $request->tanggal,
                'account_id' => $request->account,
                'kategori_id' => $request->kategori,
                'aktivitas' => $request->aktivitas,
                'jumlah' => str_replace( ',', '', $request->jumlah),
                'bukti' => empty($upload) ? '' : $upload,
                'catatan' => empty($request->catatan) ? '' : $request->catatan,
                ]
            );

            $account = Account::where('id', $request->account)->first();
            $account->saldo = $account->saldo - str_replace(',', '', $request->jumlah);
            $account->save();

            DB::commit();
        } catch (\Exception $exception) {
            DB::rollback();
            throw $exception;
        }
        
        return redirect('/hutang')->withStatus('Reimburse berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Hutang  $hutang
     * @return \Illuminate\Http\Response
     */
    public function show(Hutang $hutang)
    {
        return view('hutang.show', compact('hutang'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Hutang  $hutang
     * @return \Illuminate\Http\Response
     */
    public function edit(Hutang $hutang)
    {
        $kategori = Kategori::all();
        $account = Account::all();
        $pegawai = Pegawai::all();
        return view('hutang.edit', compact('hutang', 'pegawai', 'kategori', 'account'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Hutang  $hutang
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Hutang $hutang)
    {
        $request->validate(
            [
            'status' => 'required',
            'admin' => 'required',
            'tanggal' => 'required',
            'account' => 'required',
            'pegawai' => 'required',
            'kategori' => 'required',
            'aktivitas' => 'required|regex:/^[A-Za-z0-9&-\/ ]+$/',
            'jumlah' => 'required',
            'bukti.*' => 'image|mimes:jpeg,png,jpg|max:5120',
            ]
        );

        $file = null;

        try {
            DB::beginTransaction();
            $hutang = Hutang::find($request->id);
            $pengeluaran = Pengeluaran::where([
                ['aktivitas', $hutang->aktivitas],
                ['created_at', $hutang->created_at],
            ])->first();
            $account = Account::where('id', $hutang->account_id)->first();
            $upload = $hutang->bukti;

            if ($request->imagecheck) {
                if ($request->hasfile('bukti')) {
                    foreach (json_decode($hutang->bukti) as $foto) {
                        $data[] = $foto;
                    }
    
                    foreach ($request->imagecheck as $check) {
                        $data = array_diff($data, array($check));
                        File::delete('uploads/hutang/'.$check);
                        File::delete('uploads/pengeluaran/'.$check);
                    }
    
                    foreach ($request->file('bukti') as $file) {
                        $namafile = time() . '-' . $file->getClientOriginalName();
                        $folderhut = 'uploads/hutang/';
                        $folderkel = 'uploads/pengeluaran/';
                        $file->move('uploads/hutang', $namafile);
                        copy($folderhut.$namafile, $folderkel.$namafile);
                        $data[] = $namafile;
                    }
                } else {
                    foreach (json_decode($hutang->bukti) as $foto) {
                        $data[] = $foto;
                    }
    
                    foreach ($request->imagecheck as $check) {
                        $data = array_diff($data, array($check));
                        File::delete('uploads/hutang/'.$check);
                        File::delete('uploads/pengeluaran/'.$check);
                    }
                }
                $upload = json_encode($data);
            }
    
            if (($request->hasfile('bukti')) && (empty($request->imagecheck))) {
                if ($hutang->bukti) {
                    foreach (json_decode($hutang->bukti) as $foto) {
                        $data[] = $foto;
                    }
                }
    
                foreach ($request->file('bukti') as $file) {
                    $namafile = time() . '-' . $file->getClientOriginalName();
                    $folderhut = 'uploads/hutang/';
                    $folderkel = 'uploads/pengeluaran/';
                    $file->move('uploads/hutang', $namafile);
                    copy($folderhut.$namafile, $folderkel.$namafile);
                    $data[] = $namafile;
                }

                $upload = json_encode($data);
            }

            if ($account->id <> $request->account) {
                $accountbaru = Account::where('id', $request->account)->first();
                $account->saldo = $account->saldo + str_replace(',', '', $hutang->jumlah);
                $accountbaru->saldo = $accountbaru->saldo - str_replace(',', '', $request->jumlah);
                $accountbaru->save();
            } else {
                $account->saldo = ($account->saldo + str_replace(',', '', $hutang->jumlah)) - str_replace(',', '', $request->jumlah);
            }

            $account->save();

            $hutang->status = $request->status;
            $hutang->user_id = $request->admin;
            $hutang->tanggal = Carbon::parse($request->tanggal)->format('Y-m-d');
            $hutang->account_id = $request->account;
            $hutang->kategori_id = $request->kategori;
            $hutang->pegawai_id = $request->pegawai;
            $hutang->aktivitas = $request->aktivitas;
            $hutang->jumlah = str_replace(',', '', $request->jumlah);
            $hutang->bukti = $upload;
            $hutang->catatan = empty($request->catatan) ? '' : $request->catatan;   
            $hutang->save();

            $pengeluaran->user_id = $request->admin;
            $pengeluaran->tanggal =Carbon::parse($request->tanggal)->format('Y-m-d');
            $pengeluaran->account_id = $request->account;
            $pengeluaran->kategori_id = $request->kategori;
            $pengeluaran->aktivitas = $request->aktivitas;
            $pengeluaran->jumlah = str_replace(',', '', $request->jumlah);
            $pengeluaran->bukti = $upload;
            $pengeluaran->catatan = empty($request->catatan) ? '' : $request->catatan; 
            $pengeluaran->save();

            DB::commit();
        } catch (\Exception $exception) {
            DB::rollback();
            throw $exception;
        }

        return redirect()->route('hutang.index')->withStatus('Reimburse berhasil diupdate');
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Hutang  $hutang
     * @return \Illuminate\Http\Response
     */
    public function destroy(Hutang $hutang)
    {

resources/views/hutang/create.blade.php
@extends('_layouts.app')

@section('content')
<div class="panel-header bg-primary-gradient">
    <div class="page-inner py-5">
        <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
            <div>
                <h2 class="text-white pb-2 fw-bold">Tambah Reimburse</h2>
            </div>
            <div class="ml-md-auto py-2 py-md-0">
                <a href="{{ route('pengeluaran.index') }}" class="btn btn-white btn-border btn-round" style="border: 2px solid white !important;">
                Kembali
                </a>
            </div>
        </div>
    </div>
</div>

<div class="page-inner mt--5">
    <div class="row mt--2">
        <div class="col-md-12">
            <div class="card full-height">
                <div class="card-body">
                    <form method="post" action="{{ route('hutang.store') }}" autocomplete="off" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group{{ $errors->has('admin') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-admin">Admin</label>
                                    <select name="admin" id="input-admin" class="form-control" required>
                                        <option value="{{ auth()->user()->id }}"> {{ auth()->user()->name }} </option>
                                    </select>

                                    @if ($errors->has('admin'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('admin') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('tanggal') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-tanggal">Tanggal</label>
                                    <input type="text" name="tanggal" id="input-tanggal" class="form-control form-control-alternative{{ $errors->has('tanggal') ? ' is-invalid' : '' }}" placeholder="{{ __('Tanggal') }}" value="{{ date('d-m-Y') }}" required autofocus>

                                    @if ($errors->has('tanggal'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('tanggal') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('account') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-account">Account</label>
                                    <select name="account" id="input-account" class="form-control" required>
                                    <option value="" selected disabled> Pilih account </option>
                                        @foreach ($account as $acc)
                                            @if ( old('account') == $acc->id )
                                                <option value="{{ $acc->id }}" selected>{{ $acc->nama }}</option>
                                            @else
                                                <option value="{{ $acc->id }}">{{ $acc->nama }}</option>
                                            @endif
                                        @endforeach
                                    </select>

                                        @if ($errors->has('account'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('account') }}</strong>
                                            </span>
                                        @endif
                                </div>
                                <div class="form-group{{ $errors->has('pegawai') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-pegawai">Pegawai</label>
                                    <select name="pegawai" id="input-pegawai" class="form-control" required>
                                        <option value="" selected disabled> Pilih Pegawai </option>
                                            @foreach ($pegawai as $peg)
                                                @if ( old('pegawai') == $peg->id )
                                                    <option value="{{ $peg->id }}" selected>{{ $peg->nama }}</option>
                                                @else
                                                    <option value="{{ $peg->id }}">{{ $peg->nama }}</option>
                                                @endif
                                            @endforeach
                                    </select>

                                    @if ($errors->has('pegawai'))
                                        <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('pegawai') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-6"> 
                                <div class="form-group{{ $errors->has('kategori') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-kategori">Kategori</label>
                                    <select name="kategori" id="input-kategori" class="form-control" required>
                                        <option value="" selected disabled> Pilih kategori </option>
                                            @foreach ($kategori as $kat)
                                                @if ( old('kategori') == $kat->id )
                                                    <option value="{{ $kat->id }}" selected>{{ $kat->kategori }}</option>
                                                @else
                                                    <option value="{{ $kat->id }}">{{ $kat->kategori }}</option>
                                                @endif
                                            @endforeach
                                    </select>

                                    @if ($errors->has('kategori'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('kategori') }}</strong>
                                        </span>
                                    @endif
                                </div>                       
                                <div class="form-group{{ $errors->has('aktivitas') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-aktivitas">Aktivitas</label>
                                    <input type="text" name="aktivitas" id="input-aktivitas" class="form-control form-control-alternative{{ $errors->has('aktivitas') ? ' is-invalid' : '' }}" placeholder="{{ __('Aktivitas') }}" value="{{ old('aktivitas') }}" required>

                                    @if ($errors->has('aktivitas'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('aktivitas') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('jumlah') ? ' has-danger' : '' }}">
                                    <label for="basic-url">Jumlah</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="tanda-jumlah">Rp</span>
                                        </div>
                                        <input type="text" name="jumlah" id="input-jumlah" class="form-control form-control-alternative{{ $errors->has('jumlah') ? ' is-invalid' : '' }}" placeholder="{{ __('Jumlah') }}" value="{{ old('jumlah') }}"required>
                                        @if ($errors->has('jumlah'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('jumlah') }}</strong>
                                        </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="form-group{{ $errors->has('bukti') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-bukti">Bukti (format: png, jpg, jpeg. maks 2MB)</label>
                                    <input type="file" name="bukti[]" id="input-bukti" class="form-control-file form-control-alternative{{ $errors->has('bukti') ? ' is-invalid' : '' }}" placeholder="{{ __('Bukti') }}" value="{{ old('bukti') }}" multiple>

                                    @if ($errors->has('bukti'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('bukti') }}</strong>
                                        </span>
                                        @endif
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group{{ $errors->has('catatan') ? ' has-danger' : '' }}">
                                    <div class="mt-2 mb-2">Catatan</div>
                                    <input type="text" name="catatan" id="input-catatan" class="form-control form-control-alternative{{ $errors->has('catatan') ? ' is-invalid' : '' }}" placeholder="{{ __('Catatan') }}" value="{{ old('catatan') }}">

                                    @if ($errors->has('catatan'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('catatan') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <input type="hidden" name="status" id="status" value="Pending">
                            </div>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-success mt-4">Simpan</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>

@endsection

@push('scripts')
    <script src="https://cdn.rawgit.com/igorescobar/jQuery-Mask-Plugin/1ef022ab/dist/jquery.mask.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>  
    <script type="text/javascript">  
    $(document).ready(function(){

    // Format mata uang.
    $( '#input-jumlah' ).mask('0,000,000,000', {reverse: true});

    $('#input-tanggal').datepicker({  
        format: 'dd-mm-yyyy',
        endDate: '+0d',
        autoclose: true,
        todayHighlight: true
        });  
    })
    </script>  
@endpush

resources/views/hutang/show.blade.php
@extends('_layouts.app')

@section('styles')
<style>
.table-borderless > tbody > tr > td,
.table-borderless > tbody > tr > th,
.table-borderless > tfoot > tr > td,
.table-borderless > tfoot > tr > th,
.table-borderless > thead > tr > td,
.table-borderless > thead > tr > th {
    border: none;
}
</style>
@endsection

@section('content')
<div class="panel-header bg-primary-gradient">
    <div class="page-inner py-5">
        <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
            <div>
                <h2 class="text-white pb-2 fw-bold">Detail Reimburse</h2>
            </div>
            <div class="ml-md-auto py-2 py-md-0">
                <a href="/hutang" class="btn btn-white btn-border btn-round" style="border: 2px solid white !important;">
                Kembali
                </a>
            </div>
        </div>
    </div>
</div>

<div class="page-inner mt--5">
    <div class="row mt--2">
        <div class="col-md-12">
            <div class="card full-height">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <table class="table table-borderless">
                                <thead>
                                    <tr>
                                    <th width="40px">Status</th>
                                    <td>: {{ $hutang->status}}</td>
                                    </tr>
                                </thead>
                                <thead>
                                    <tr>
                                    <th width="40px">Admin</th>
                                    <td>: {{ $hutang->user->name}}</td>
                                    </tr>
                                </thead>
                                <thead>
                                    <tr>
                                    <th width="40px">Tanggal</th>
                                    <td>: {{ Carbon\Carbon::parse($hutang->tanggal)->format('d-m-Y') }}</td>
                                    </tr>
                                </thead> 
                                <thead>
                                    <tr>
                                    <th width="40px">Account</th>
                                    <td>: {{ $hutang->account->nama }}</td>
                                    </tr>
                                </thead>
                                <thead>
                                    <tr>
                                    <th width="40px">Pegawai</th>
                                    <td>: {{ $hutang->pegawai->nama }}</td>
                                    </tr>
                                </thead>
                                <thead>
                                    <tr>
                                    <th width="40px">Kategori</th>
                                    <td>: {{ $hutang->kategori->kategori }}</td>
                                    </tr>
                                </thead> 
                                <thead>
                                    <tr>
                                    <th width="40px">Aktivitas</th>
                                    <td>: {{ $hutang->aktivitas }}</td>
                                    </tr>
                                </thead> 
                                <thead>
                                    <tr>
                                    <th width="40px">Jumlah</th>
                                    <td>: Rp {{ $hutang->jumlah }}</td>
                                    </tr>
                                </thead>    
                                <thead>
                                    <tr>
                                        <th width="40px">Catatan</th>
                                        <td>: {{ $hutang->catatan }}</td>
                                    </tr>
                                </thead>                              
                            </table>    
                        </div>
                        <div class="col-md-6">
                            <table class="table table-borderless">
                                <thead>
                                    <tr>
                                        <th width="40px">Bukti</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>
                                            @if ($hutang->bukti)
                                                @foreach(json_decode($hutang->bukti) as $foto)
                                                <button type="button" class="btn" data-toggle="modal" data-target="#exampleModal">
                                                <img class="img" src="/uploads/hutang/{{ $foto }}" alt="bukti" width="250px">
                                                </button>
                                                @endforeach
                                            @else
                                                Bukti kosong
                                            @endif
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    @if ($hutang->status == 'Pending')
                    <div class="text-center">
                        <a href="{{ route('hutang.edit', $hutang) }}" class="btn btn-warning">
                            Edit
                        </a>
                    </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <button type="button" class="close py-2" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        <img id="img01" alt="bukti" style="width:100%">
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>

@endsection

@push('scripts')
<script>
$(document).ready(function(){
    var modal = document.getElementById('exampleModal');

    var img = $('.img');
    var modalImg = $("#img01");
    $('.img').click(function(){
    modal.style.display = "block";
    var newSrc = this.src;
    modalImg.attr('src', newSrc);
    }); 
});
</script>
@endpush