routes/web.php
<?php

Route::get('/', function () {
    return redirect('home');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
	Route::get('/home', 'HomeController@index')->name('home');
	Route::resource('pegawai', 'PegawaiController', ['except' => ['show']]);
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::resource('account', 'AccountController');
	Route::resource('kategori', 'KategoriController', ['except' => ['show']]);
	Route::resource('pemasukan', 'PemasukanController');
	Route::resource('pengeluaran', 'PengeluaranController');
	Route::resource('hutang', 'HutangController');
	Route::get('laporan', 'LaporanController@index')->name('laporan');
	Route::get('/startdate/{startdate}/enddate/{enddate}/jenis/{jenis}', ['as' => 'laporanpdf', 'uses' => 'LaporanController@laporanPDF']);
	Route::get('/table/pegawai', 'PegawaiController@dataTable')->name('table.pegawai');
	Route::get('/table/kategori', 'KategoriController@dataTable')->name('table.kategori');
	Route::get('/table/pemasukan', 'PemasukanController@dataTable')->name('table.pemasukan');
	Route::get('/table/pengeluaran', 'PengeluaranController@dataTable')->name('table.pengeluaran');
	Route::get('/table/hutang', 'HutangController@dataTable')->name('table.hutang');
	Route::get('/dashboard/countdata', 'DashboardController@dataHeader');
});

app/Pegawai.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pegawai extends Model
{
	protected $table = 'pegawai';

    protected $fillable = [
        'id',
        'nama',
        'jabatan',
        'created_at',
    ];

    protected $hidden = [
    	'updated_at',
    	'deleted_at',
    ];
}

app/Http/Controllers/PegawaiController.php
<?php

namespace App\Http\Controllers;

use App\Pegawai;
use Illuminate\Http\Request;
use DataTables;

class PegawaiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pegawai = Pegawai::all();
        return view('pegawai.index', ['pegawai' => $pegawai]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pegawai.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required|regex:/^[A-Za-z ]+$/',
            'jabatan' => 'required|regex:/^[A-Za-z&-\/ ]+$/',
        ]);

        Pegawai::create([
            'nama' => $request->nama,
            'jabatan' => $request->jabatan,
        ]);

        return redirect('/pegawai')->withStatus('Pegawai berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Pegawai  $pegawai
     * @return \Illuminate\Http\Response
     */
    public function show(Pegawai $pegawai)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Pegawai  $pegawai
     * @return \Illuminate\Http\Response
     */
    public function edit(Pegawai $pegawai)
    {
        return view('pegawai.edit', compact('pegawai'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Pegawai  $pegawai
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Pegawai $pegawai)
    {
        $request->validate([
            'nama' => 'required|regex:/^[A-Za-z ]+$/',
            'jabatan' => 'required|regex:/^[A-Za-z&-\/ ]+$/',
        ]);

        $pegawai->update($request->all());

        return redirect()->route('pegawai.index')->withStatus('Pegawai berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Pegawai  $pegawai
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pegawai $pegawai)
    {
        $pegawai->delete();

        return redirect()->route('pegawai.index')->withStatus('Data berhasil dihapus');
    }

    public function dataTable()
    {
        $model = Pegawai::query();
        return DataTables::of($model)
            ->addColumn('action', function ($model) {
                return '
                <a href="'. route('pegawai.edit', $model->id) . '" class="btn btn-warning btn-xs"><i class="fas fa-pen"></i></a>  
                <button class="btn btn-xs btn-danger btn-delete" data-remote="/pegawai/' . $model->id . '"><i class="fas fa-trash"></i></button>';
            })
            ->addIndexColumn()
            ->rawColumns(['action'])
            ->make(true);
    }
}

resources/views/pegawai/create.blade.php
@extends('_layouts.app')

@section('content')
<div class="panel-header bg-primary-gradient">
    <div class="page-inner py-5">
        <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
            <div>
                <h2 class="text-white pb-2 fw-bold">Tambah Pegawai</h2>
            </div>
            <div class="ml-md-auto py-2 py-md-0">
                <a href="/pegawai" class="btn btn-white btn-border btn-round" style="border: 2px solid white !important;">
                 Kembali
                </a>
            </div>
        </div>
    </div>
</div>

<div class="page-inner mt--5">
    <div class="row mt--2">
        <div class="col-md-12">
            <div class="card full-height">
                <div class="card-body">
                    <div class="container-fluid mt--7">
                        <div class="row">
                            <div class="col-xl-12 order-xl-1">
                                <form method="post" action="{{ route('pegawai.store') }}" autocomplete="off">
                                @csrf
                                    <div class="pl-lg-4">
                                        <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                            <label class="form-control-label" for="input-nama">Nama</label>
                                            <input type="text" name="nama" id="input-nama" class="form-control form-control-alternative{{ $errors->has('nama') ? ' is-invalid' : '' }}" placeholder="{{ __('Nama') }}" value="{{ old('nama') }}" required autofocus>

                                        @if ($errors->has('nama'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('nama') }}</strong>
                                            </span>
                                        @endif
                                        </div>
                                        <div class="form-group{{ $errors->has('jabatan') ? ' has-danger' : '' }}">
                                            <label class="form-control-label" for="input-jabatan">Jabatan</label>
                                            <input type="text" name="jabatan" id="input-jabatan" class="form-control form-control-alternative{{ $errors->has('jabatan') ? ' is-invalid' : '' }}" placeholder="{{ __('Jabatan') }}" value="{{ old('jabatan') }}" required>

                                            @if ($errors->has('jabatan'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('jabatan') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    <div class="text-center">
                                        <button type="submit" class="btn btn-success mt-4">Simpan</button>
                                    </div>
                                </div>
                            </form>     
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="atlantis/js/core/jquery.3.2.1.min.js"></script>
@endsection

resources/views/pegawai/edit.blade.php
@extends('_layouts.app')

@section('content')
<div class="panel-header bg-primary-gradient">
    <div class="page-inner py-5">
        <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
            <div>
                <h2 class="text-white pb-2 fw-bold">Edit Pegawai</h2>
            </div>
            <div class="ml-md-auto py-2 py-md-0">
                <a href="/pegawai" class="btn btn-white btn-border btn-round" style="border: 2px solid white !important;">
                 Kembali
                </a>
            </div>
        </div>
    </div>
</div>

<div class="page-inner mt--5">
    <div class="row mt--2">
        <div class="col-md-12">
            <div class="card full-height">
                <div class="card-body">
                    <div class="container-fluid mt--7">
                        <div class="row">
                            <div class="col-xl-12 order-xl-1">      
                                <div class="card-body">
                                    <form method="post" action="{{ route('pegawai.update', $pegawai) }}" autocomplete="off">
                                        @csrf
                                        @method('put')
                                        <div class="pl-lg-4">
                                            <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                                <label class="form-control-label" for="input-nama">Nama</label>
                                                <input type="text" name="nama" id="input-nama" class="form-control form-control-alternative{{ $errors->has('nama') ? ' is-invalid' : '' }}" placeholder="{{ __('Nama') }}" value="{{ old('nama', $pegawai->nama) }}" required autofocus>

                                                @if ($errors->has('nama'))
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $errors->first('nama') }}</strong>
                                                    </span>
                                                @endif
                                            </div>
                                            <div class="form-group{{ $errors->has('jabatan') ? ' has-danger' : '' }}">
                                                <label class="form-control-label" for="input-jabatan">Jabatan</label>
                                                <input type="text" name="jabatan" id="input-jabatan" class="form-control form-control-alternative{{ $errors->has('jabatan') ? ' is-invalid' : '' }}" placeholder="{{ __('Jabatan') }}" value="{{ old('jabatan', $pegawai->jabatan) }}" required>

                                                @if ($errors->has('jabatan'))
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $errors->first('jabatan') }}</strong>
                                                    </span>
                                                @endif
                                            </div>
                                            <div class="text-center">
                                                <button type="submit" class="btn btn-success mt-4">Simpan</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pegawai/index.blade.php
@extends('_layouts.app')

@section('content')
<div class="panel-header bg-primary-gradient">
    <div class="page-inner py-5">
        <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
            <div>
                <h2 class="text-white pb-2 fw-bold">Daftar Pegawai</h2>
            </div>
            <div class="ml-md-auto py-2 py-md-0">
                <a href="/pegawai/create" class="btn btn-white btn-border btn-round" style="border: 2px solid white !important;">
                <i class="la flaticon-add-user"></i> Tambah Pegawai
                </a>
            </div>
        </div>
    </div>
</div>

<div class="page-inner mt--5">
    <div class="row mt--2">
        <div class="col-md-12">
            <div class="card full-height">
                <div class="card-body">                  
                    <div class="col-12">
                        @if (session('status'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ session('status') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endif
                    </div>
                <div class="table-responsive">
                    <table id="basic-datatables" class="display table table-striped" width="100%">
                        <thead>
                            <tr>
                                <th scope="col">No.</th>
                                <th scope="col">Nama</th>
                                <th scope="col">Jabatan</th>
                                <th scope="col"><i class="icon-grid"></i></th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="atlantis/js/core/jquery.3.2.1.min.js"></script>
@endsection

@push('scripts')
<script src="atlantis/js/plugin/datatables/datatables.min.js"></script>

<script>
    $(document).ready(function() {
        $('#basic-datatables').DataTable({
            responsive: true,
            processing: true,
            serverSide: true,
            ajax: "{{ route('table.pegawai') }}",
            columns: [
                {data: 'DT_RowIndex', name: 'id', class: 'text-center', width: '50px'},
                {data: 'nama', name:'nama', class: 'text-center'},
                {data: 'jabatan', name:'jabatan', class: 'text-center'},
                {data: 'action', name: 'action', width: '80px', class: 'text-center'}
            ]
        });

        $('#basic-datatables').on('click', '.btn-delete[data-remote]', function (e) { 
            e.preventDefault();
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            var url = $(this).data('remote');
            // confirm then
            if (confirm('Yakin ingin menghapus?')) {
                $.ajax({
                    url: url,
                    type: 'DELETE',
                    dataType: 'json',
                    data: {method: 'DELETE', submit: true}
                }).always(function (data) {
                    swal({
                    title: 'Data berhasil dihapus',
                    type: 'success',
                    icon: 'success'
                    });
                    $('#basic-datatables').DataTable().draw(false);
                });
            }
        });
    });
</script>

@endpush